
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/dati_base?serverTimezone=GMT%2B8
      username: root
      password: 1234
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  redis:
    host: 127.0.0.1
    port: 6379
  application:
    name: user-management
mybatis:
  mapper-locations: com/dati/dao/*.xml
  configuration:
    lazy-loading-enabled: false
server:
  port: 10006
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10002/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
