server:
  port: 10002
spring:
  application:
    name: registry-service
eureka:
  client:
    service-url:
        defaultZone: http://127.0.0.1:10002/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1