server:
  port: 10001
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  application:
    name: gateway-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10002/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
ribbon:
  connectionTimeout: 1000
  ReadTimeout: 2500
  MaxAutoRetries: 0
  MaxAutoRetriesNextserver: 0
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
zuul:
  prefix: /api
  routes:
    topic:
      strip-prefix: false
      path: /topic/**
      serviceId: topic-management

    user-manage:
      strip-prefix: false
      path: /manage/**
      serviceId: user-management
  sensitive-headers:
#zuul默认会过滤敏感一些请求头，可以指定不过滤。
    - Cookie,Set-Cookie,Authorization
cors:
  prop:
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
    allowedOrigins:
      - http://127.0.0.1:8080
    maxAge: 604800000